// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var MoviePanel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      this.$scope = $scope;
      this.$http = $http;
      this.search = __bind(this.search, this);
      this.$scope.search = this.search;
    }

    MoviePanel.prototype.search = function() {
      var _this = this;

      this.searchTerm = this.$scope.searchInput;
      console.log(this.searchTerm);
      if (this.searchTerm) {
        return this.$http({
          url: "http://www.omdbapi.com/",
          method: "get",
          params: {
            s: this.searchTerm
          }
        }).success(function(data, status, headers, config) {
          return _this.$scope.results = data['Search'];
        });
      }
    };

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", '$http'];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
